USE [master]
GO

/****** Object:  Database [DevisFacturation]    Script Date: 18/07/2018 17:19:29 ******/
CREATE DATABASE [DevisFacturation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'_', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.TOMSQL\MSSQL\DATA\_gzeuimzmhj.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'__log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.TOMSQL\MSSQL\DATA\__logrgzergzer.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DevisFacturation] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevisFacturation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DevisFacturation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DevisFacturation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DevisFacturation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DevisFacturation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DevisFacturation] SET ARITHABORT OFF 
GO

ALTER DATABASE [DevisFacturation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DevisFacturation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DevisFacturation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DevisFacturation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DevisFacturation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DevisFacturation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DevisFacturation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DevisFacturation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DevisFacturation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DevisFacturation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DevisFacturation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DevisFacturation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DevisFacturation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DevisFacturation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DevisFacturation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DevisFacturation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DevisFacturation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DevisFacturation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DevisFacturation] SET  MULTI_USER 
GO

ALTER DATABASE [DevisFacturation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DevisFacturation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DevisFacturation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DevisFacturation] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DevisFacturation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DevisFacturation] SET  READ_WRITE 
GO


