//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Facturation
    {
        public long ID { get; set; }
        public long Numéro { get; set; }
        public System.DateTime Mois { get; set; }
        public decimal Montant { get; set; }
        public long FK_Devis { get; set; }
    
    [JsonIgnore]
        public virtual Devis Devis { get; set; }
    }
}
