//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevisFacturationEntities : DbContext
    {
        public DevisFacturationEntities()
            : base("name=DevisFacturationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Projet> Projet { get; set; }
        public virtual DbSet<Stories_d> Stories_d { get; set; }
        public virtual DbSet<Stories_Devis> Stories_Devis { get; set; }
        public virtual DbSet<Stories_f> Stories_f { get; set; }
        public virtual DbSet<Stories_Facturation> Stories_Facturation { get; set; }
        public virtual DbSet<Tarification_Ressource> Tarification_Ressource { get; set; }
        public virtual DbSet<Tasks_d> Tasks_d { get; set; }
        public virtual DbSet<Tasks_f> Tasks_f { get; set; }
        public virtual DbSet<Tarification> Tarification { get; set; }
        public virtual DbSet<Ressource> Ressource { get; set; }
        public virtual DbSet<Paramètres> Paramètres { get; set; }
        public virtual DbSet<Devis> Devis { get; set; }
        public virtual DbSet<Facturation> Facturation { get; set; }
    }
}
