//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RessTarif
    {
        public string Name { get; set; }
        public Nullable<int> Niveau { get; set; }
        public bool Obsolete { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Tar3 { get; set; }
        public decimal Tar5 { get; set; }
        public Nullable<bool> IsAmo { get; set; }
        public long FK_Ressource { get; set; }
        public long FK_Tarification { get; set; }
    }
}
