//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Stories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stories()
        {
            this.Stories_Devis = new HashSet<Stories_Devis>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public long ID { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> UpdatetDate { get; set; }
        public string Owners { get; set; }
        public string Labels { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public Nullable<bool> Bonus { get; set; }
        public Nullable<long> OriginalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
        public virtual ICollection<Stories_Devis> Stories_Devis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
