//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stories_Devis
    {
        public long ID { get; set; }
        public long FK_Stories_d { get; set; }
        public long FK_Devis { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Devis Devis { get; set; }
        public virtual Stories_d Stories_d { get; set; }
    }
}
