//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks_d
    {
        private MasterTasks t;

        public Tasks_d(MasterTasks t)
        {
            this.t = t;
        }

        public long ID { get; set; }
        public long FK_Stories_d { get; set; }
        public string Description { get; set; }
        public string Initials { get; set; }
        public string Duration { get; set; }
        public string Fk_Ressource_Initials { get; set; }
    
        public virtual Stories_d Stories_d { get; set; }
    }
}
